source 'https://rubygems.org/'

gem 'rake'

gem 'rspec' # tests, baby
gem 'rack-test'
gem 'faye-websocket' # websockets for listening to blockchain.info
gem 'eventmachine'

gem 'sequel'
gem 'pg'

gem 'sinatra'
gem 'unicorn' # for production
gem 'shotgun' # for development

gem 'github-markdown'
gem 'github-markup', git: 'https://github.com/github/markup.git'
gem 'bcrypt'    # for password hashing
