require_relative 'lib/app'

require 'rspec/core/rake_task'

desc 'Opens an IRB console'
task :console do
  require 'irb'
  require 'irb/completion'
  App.configure! ENV['CHROMA_ENV']
  ARGV.clear
  IRB.start
end

namespace :test do

  desc 'Tests only lib/'
  RSpec::Core::RakeTask.new(:lib) do |t|
    t.pattern = "lib/spec/**/*_spec.rb"
  end

  desc 'Tests only api/'
  RSpec::Core::RakeTask.new(:api) do |t|
    t.pattern = "api/v1/spec/**/*_spec.rb"
  end
  
  desc 'Runs all tests'
  task :all => ["test:lib", "test:api"]

end

namespace :db do

  desc 'Run migrations'
  task :migrate => ["db:connect"] do
    Sequel.extension :migration
    if ENV['VERSION']
      Sequel::Migrator.run( App.db, "db/migrations", target: ENV['VERSION'].to_i )
    else
      Sequel::Migrator.run( App.db, "db/migrations" )
    end
  end

  task :connect do
    @env = ENV['CHROMA_ENV'] || "vagrant"
    App.configure!( @env )
  end
  
end
