require_relative 'lib/app'

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new("test:lib") do |t|
  t.pattern = "lib/spec/**/*_spec.rb"
end

namespace :db do

  task 'Run migrations'
  task :migrate => ["db:connect"] do
    Sequel.extension :migration
    if ENV['VERSION']
      Sequel::Migrator.run( App.db, "db/migrations", target: ENV['VERSION'].to_i )
    else
      Sequel::Migrator.run( App.db, "db/migrations" )
    end
  end

  task :connect do
    @env = ENV['CHROMA_ENV'] || "vagrant"
    App.configure!( @env )
  end
  
end
